name: testlsbrelease

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: lsbreleasetest
      run: apt-get install lsb-release
